/*
 * Auto-generated host launcher (two inputs): launches the k_custom kernel on the simulated Ascend device.
 * Inputs are filled with the constants x=1.0 y=2.0; after the run the host-side verify expects ~ 2.0. dtype=float.
 */
#include <cstdio>
#include <cstdint>
#include <cmath>
#include <cstdlib>   // getenv (golden bridge)
#include "acl/acl.h"
#include "aclrtlaunch_k_custom.h"  // auto-generated by ascendc_library

#define CHECK_ACL(x)                                                                   \
    do {                                                                               \
        aclError __ret = (x);                                                          \
        if (__ret != ACL_SUCCESS) {                                                    \
            printf("[ERROR] %s:%d acl ret = %d\n", __FILE__, __LINE__, (int)__ret);    \
            return 1;                                                                  \
        }                                                                              \
    } while (0)

int32_t main()
{
    const uint32_t blockDim = 8;
    const int32_t totalLen = 8 * 2048;
    const size_t byteSize = (size_t)totalLen * sizeof(float);

    CHECK_ACL(aclInit(nullptr));
    CHECK_ACL(aclrtSetDevice(0));
    aclrtStream stream = nullptr;
    CHECK_ACL(aclrtCreateStream(&stream));

    float *xHost = nullptr, *yHost = nullptr, *zHost = nullptr;
    uint8_t *xDev = nullptr, *yDev = nullptr, *zDev = nullptr;
    CHECK_ACL(aclrtMallocHost((void **)&xHost, byteSize));
    CHECK_ACL(aclrtMallocHost((void **)&yHost, byteSize));
    CHECK_ACL(aclrtMallocHost((void **)&zHost, byteSize));
    CHECK_ACL(aclrtMalloc((void **)&xDev, byteSize, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&yDev, byteSize, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&zDev, byteSize, ACL_MEM_MALLOC_HUGE_FIRST));

    for (int32_t i = 0; i < totalLen; i++) { xHost[i] = (float)(1.0); yHost[i] = (float)(2.0); }
    // golden bridge: if GOLDEN_IN_X/Y are set, read inputs from fp32 raw files to override the constants (shares the same random data with an external cross-check party)
    bool golden = false;
    { const char *gx = getenv("GOLDEN_IN_X"), *gy = getenv("GOLDEN_IN_Y");
      if (gx && gy) { FILE *fx = fopen(gx, "rb"), *fy = fopen(gy, "rb");
        if (fx && fy && fread(xHost, sizeof(float), totalLen, fx) == (size_t)totalLen
                     && fread(yHost, sizeof(float), totalLen, fy) == (size_t)totalLen) golden = true;
        if (fx) fclose(fx); if (fy) fclose(fy); } }
    CHECK_ACL(aclrtMemcpy(xDev, byteSize, xHost, byteSize, ACL_MEMCPY_HOST_TO_DEVICE));
    CHECK_ACL(aclrtMemcpy(yDev, byteSize, yHost, byteSize, ACL_MEMCPY_HOST_TO_DEVICE));

    ACLRT_LAUNCH_KERNEL(k_custom)(blockDim, stream, xDev, yDev, zDev);
    CHECK_ACL(aclrtSynchronizeStream(stream));

    CHECK_ACL(aclrtMemcpy(zHost, byteSize, zDev, byteSize, ACL_MEMCPY_DEVICE_TO_HOST));

    // golden bridge: dump the output tensor (fp32 raw) for an external cross-check party to use as the Ascend simulation golden
    if (golden) { const char *go = getenv("GOLDEN_OUT");
      if (go) { FILE *fo = fopen(go, "wb"); if (fo) { fwrite(zHost, sizeof(float), totalLen, fo); fclose(fo); printf("[GOLDEN] dumped %d floats to %s\n", totalLen, go); } } }

    const float expect = (float)(2.0);
    int errors = 0;
    for (int32_t i = 0; !golden && i < totalLen; i++) {   // in golden mode skip the constant self-check (inputs are external random data)
        float v = zHost[i];
        if (fabsf(v - expect) > 1e-3f) {
            if (errors < 5) printf("[CHECK] idx %d = %f (expect %f)\n", i, v, expect);
            errors++;
        }
    }
    printf("z[0]=%f z[last]=%f total=%d errors=%d\n", zHost[0], zHost[totalLen - 1], totalLen, errors);

    // Emit the PASS/FAIL marker BEFORE ACL teardown: on some hosts aclFinalize()
    // ends the process / closes the simulator's stdout capture, so a marker printed
    // afterwards is never recorded. errors is already final here.
    if (errors == 0) printf("MAX SIMULATION PASSED\n");
    else             printf("MAX SIMULATION FAILED (%d errors)\n", errors);
    fflush(stdout);

    CHECK_ACL(aclrtFree(xDev));
    CHECK_ACL(aclrtFree(yDev));
    CHECK_ACL(aclrtFree(zDev));
    CHECK_ACL(aclrtFreeHost(xHost));
    CHECK_ACL(aclrtFreeHost(yHost));
    CHECK_ACL(aclrtFreeHost(zHost));
    CHECK_ACL(aclrtDestroyStream(stream));
    CHECK_ACL(aclrtResetDevice(0));
    CHECK_ACL(aclFinalize());

    return errors == 0 ? 0 : 1;
}
