#!/usr/bin/env python3
"""
aggregate.py — scan all units under examples/ and aggregate them into the reports/INDEX.md summary table.
Extracts status/instruction count/time/report links from each unit's meta.json + RESULT.md.
"""
import json
import os
import platform
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXAMPLES = os.path.join(ROOT, "examples")

# Tag outputs by host CPU arch so a run on one host never clobbers another host's
# committed baseline. aarch64 keeps the original unsuffixed names (RESULT.md /
# reports/INDEX.md, the repo's committed ARM baseline); other arches get a suffix.
REPORT_ARCH = os.environ.get("REPORT_ARCH") or platform.machine()
_SUFFIX = "" if REPORT_ARCH == "aarch64" else "." + REPORT_ARCH
RESULT_NAME = "RESULT%s.md" % _SUFFIX
OUT = os.path.join(ROOT, "reports", "INDEX%s.md" % _SUFFIX)


def parse_result(path):
    """Extract status/instr/time from RESULT.md."""
    d = {"status": "—", "instr": "—", "time": "—"}
    if not os.path.exists(path):
        return d
    txt = open(path).read()
    m = re.search(r"Status: \*\*(\w+)\*\*", txt)
    if m:
        d["status"] = m.group(1)
    m = re.search(r"Instruction count: ([\d\-]+)", txt)
    if m:
        d["instr"] = m.group(1)
    m = re.search(r"Execution time \(ns\): ([\d.\-]+)", txt)
    if m:
        d["time"] = m.group(1)
    return d


def main():
    units = []
    for dirpath, _, files in os.walk(EXAMPLES):
        if "meta.json" not in files:
            continue
        meta = json.load(open(os.path.join(dirpath, "meta.json")))
        res = parse_result(os.path.join(dirpath, RESULT_NAME))
        reldir = os.path.relpath(dirpath, ROOT)
        units.append((meta, res, reldir))

    units.sort(key=lambda u: (u[0]["category"], u[0]["name"]))

    emoji = {"passed": "✅", "build_failed": "🔧", "sim_failed": "❌",
             "no_exe": "❌", "unknown": "⬜", "—": "⬜"}
    npass = sum(1 for _, r, _ in units if r["status"] == "passed")

    lines = []
    lines.append("# CANN API Explorer — simulation results summary (%s)" % REPORT_ARCH)
    lines.append("")
    lines.append("Auto-generated by `harness/aggregate.py` on host arch `%s`. %d units, %d passed." % (REPORT_ARCH, len(units), npass))
    lines.append("")
    lines.append("| Status | API | Category | arity | dtype | Instr count | Time(ns) | Result | Doc |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for meta, res, reldir in units:
        e = emoji.get(res["status"], "⬜")
        doc = "[doc](%s)" % meta["doc_url"] if meta.get("doc_url") else "—"
        result_link = "[RESULT](../%s/%s)" % (reldir, RESULT_NAME)
        lines.append("| %s %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            e, res["status"], meta["name"], meta["category"], meta["arity"],
            meta["dtype"], res["instr"], res["time"], result_link, doc))
    lines.append("")
    lines.append("Legend: ✅ passed · ❌ simulation failed · 🔧 build failed · ⬜ not run")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("Wrote %s (%d units, %d passed)" % (os.path.relpath(OUT, ROOT), len(units), npass))


if __name__ == "__main__":
    main()
