/*
 * Host launcher for the Where unit (four buffers): src0, src1, condition (bool), dst.
 * src0 = 1.0, src1 = 2.0, condition[i] = (i even). Expected: dst[i] = (i even) ? 1.0 : 2.0.
 */
#include <cstdio>
#include <cstdint>
#include <cmath>
#include "acl/acl.h"
#include "aclrtlaunch_k_custom.h"  // auto-generated by ascendc_library

#define CHECK_ACL(x)                                                                   \
    do {                                                                               \
        aclError __ret = (x);                                                          \
        if (__ret != ACL_SUCCESS) {                                                    \
            printf("[ERROR] %s:%d acl ret = %d\n", __FILE__, __LINE__, (int)__ret);    \
            return 1;                                                                  \
        }                                                                              \
    } while (0)

int32_t main()
{
    const int32_t elem = 512;
    const size_t fBytes = (size_t)elem * sizeof(float);
    const size_t cBytes = (size_t)elem * sizeof(uint8_t); // bool is 1 byte

    CHECK_ACL(aclInit(nullptr));
    CHECK_ACL(aclrtSetDevice(0));
    aclrtStream stream = nullptr;
    CHECK_ACL(aclrtCreateStream(&stream));

    float *s0Host = nullptr, *s1Host = nullptr, *dHost = nullptr;
    uint8_t *cHost = nullptr;
    uint8_t *s0Dev = nullptr, *s1Dev = nullptr, *cDev = nullptr, *dDev = nullptr;
    CHECK_ACL(aclrtMallocHost((void **)&s0Host, fBytes));
    CHECK_ACL(aclrtMallocHost((void **)&s1Host, fBytes));
    CHECK_ACL(aclrtMallocHost((void **)&dHost, fBytes));
    CHECK_ACL(aclrtMallocHost((void **)&cHost, cBytes));
    CHECK_ACL(aclrtMalloc((void **)&s0Dev, fBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&s1Dev, fBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&cDev, cBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&dDev, fBytes, ACL_MEM_MALLOC_HUGE_FIRST));

    for (int32_t i = 0; i < elem; i++) {
        s0Host[i] = 1.0f;
        s1Host[i] = 2.0f;
        cHost[i] = (uint8_t)((i % 2) == 0 ? 1 : 0);
    }
    CHECK_ACL(aclrtMemcpy(s0Dev, fBytes, s0Host, fBytes, ACL_MEMCPY_HOST_TO_DEVICE));
    CHECK_ACL(aclrtMemcpy(s1Dev, fBytes, s1Host, fBytes, ACL_MEMCPY_HOST_TO_DEVICE));
    CHECK_ACL(aclrtMemcpy(cDev, cBytes, cHost, cBytes, ACL_MEMCPY_HOST_TO_DEVICE));

    ACLRT_LAUNCH_KERNEL(k_custom)(1, stream, s0Dev, s1Dev, cDev, dDev);
    CHECK_ACL(aclrtSynchronizeStream(stream));

    CHECK_ACL(aclrtMemcpy(dHost, fBytes, dDev, fBytes, ACL_MEMCPY_DEVICE_TO_HOST));

    int errors = 0;
    for (int32_t i = 0; i < elem; i++) {
        float expect = ((i % 2) == 0) ? 1.0f : 2.0f;
        if (fabsf(dHost[i] - expect) > 1e-3f) {
            if (errors < 5) printf("[CHECK] idx %d = %f (expect %f)\n", i, dHost[i], expect);
            errors++;
        }
    }
    printf("dst[0]=%f dst[1]=%f dst[2]=%f errors=%d\n", dHost[0], dHost[1], dHost[2], errors);

    // Emit the PASS/FAIL marker BEFORE ACL teardown.
    if (errors == 0) printf("WHERE SIMULATION PASSED\n");
    else             printf("WHERE SIMULATION FAILED (%d errors)\n", errors);
    fflush(stdout);

    CHECK_ACL(aclrtFree(s0Dev));
    CHECK_ACL(aclrtFree(s1Dev));
    CHECK_ACL(aclrtFree(cDev));
    CHECK_ACL(aclrtFree(dDev));
    CHECK_ACL(aclrtFreeHost(s0Host));
    CHECK_ACL(aclrtFreeHost(s1Host));
    CHECK_ACL(aclrtFreeHost(cHost));
    CHECK_ACL(aclrtFreeHost(dHost));
    CHECK_ACL(aclrtDestroyStream(stream));
    CHECK_ACL(aclrtResetDevice(0));
    CHECK_ACL(aclFinalize());

    return errors == 0 ? 0 : 1;
}
