/*
 * Host launcher (single input): launches the k_custom kernel on the simulated Ascend device.
 * Input src=0.0 (float); output is bool. LogicalNot(0) -> 1 (true).
 */
#include <cstdio>
#include <cstdint>
#include "acl/acl.h"
#include "aclrtlaunch_k_custom.h"  // auto-generated by ascendc_library

#define CHECK_ACL(x)                                                                   \
    do {                                                                               \
        aclError __ret = (x);                                                          \
        if (__ret != ACL_SUCCESS) {                                                    \
            printf("[ERROR] %s:%d acl ret = %d\n", __FILE__, __LINE__, (int)__ret);    \
            return 1;                                                                  \
        }                                                                              \
    } while (0)

int32_t main()
{
    const uint32_t blockDim = 8;
    const int32_t totalLen = 8 * 2048;
    const size_t srcBytes = (size_t)totalLen * sizeof(float);
    const size_t dstBytes = (size_t)totalLen * sizeof(uint8_t);

    CHECK_ACL(aclInit(nullptr));
    CHECK_ACL(aclrtSetDevice(0));
    aclrtStream stream = nullptr;
    CHECK_ACL(aclrtCreateStream(&stream));

    float *sHost = nullptr;
    uint8_t *dHost = nullptr;
    uint8_t *sDev = nullptr, *dDev = nullptr;
    CHECK_ACL(aclrtMallocHost((void **)&sHost, srcBytes));
    CHECK_ACL(aclrtMallocHost((void **)&dHost, dstBytes));
    CHECK_ACL(aclrtMalloc((void **)&sDev, srcBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&dDev, dstBytes, ACL_MEM_MALLOC_HUGE_FIRST));

    for (int32_t i = 0; i < totalLen; i++) sHost[i] = 0.0f;
    CHECK_ACL(aclrtMemcpy(sDev, srcBytes, sHost, srcBytes, ACL_MEMCPY_HOST_TO_DEVICE));

    ACLRT_LAUNCH_KERNEL(k_custom)(blockDim, stream, sDev, dDev);
    CHECK_ACL(aclrtSynchronizeStream(stream));

    CHECK_ACL(aclrtMemcpy(dHost, dstBytes, dDev, dstBytes, ACL_MEMCPY_DEVICE_TO_HOST));

    const uint8_t expect = 1;  // !(0 != 0) -> true
    int errors = 0;
    for (int32_t i = 0; i < totalLen; i++) {
        if (dHost[i] != expect) {
            if (errors < 5) printf("[CHECK] idx %d = %u (expect %u)\n", i, dHost[i], expect);
            errors++;
        }
    }
    printf("dst[0]=%u dst[last]=%u total=%d errors=%d\n", dHost[0], dHost[totalLen - 1], totalLen, errors);

    if (errors == 0) printf("LOGICAL_NOT SIMULATION PASSED\n");
    else             printf("LOGICAL_NOT SIMULATION FAILED (%d errors)\n", errors);
    fflush(stdout);

    CHECK_ACL(aclrtFree(sDev));
    CHECK_ACL(aclrtFree(dDev));
    CHECK_ACL(aclrtFreeHost(sHost));
    CHECK_ACL(aclrtFreeHost(dHost));
    CHECK_ACL(aclrtDestroyStream(stream));
    CHECK_ACL(aclrtResetDevice(0));
    CHECK_ACL(aclFinalize());

    return errors == 0 ? 0 : 1;
}
