/*
 * Host launcher for the CumSum unit (three buffers): src, dst, lastRow.
 * src is a [16,16] all-ones tensor. Last-axis prefix sum makes each output row
 * [1,2,3,...,16], and lastRow (prefix sum of the final input row) is also [1,2,...,16].
 */
#include <cstdio>
#include <cstdint>
#include <cmath>
#include "acl/acl.h"
#include "aclrtlaunch_k_custom.h"  // auto-generated by ascendc_library

#define CHECK_ACL(x)                                                                   \
    do {                                                                               \
        aclError __ret = (x);                                                          \
        if (__ret != ACL_SUCCESS) {                                                    \
            printf("[ERROR] %s:%d acl ret = %d\n", __FILE__, __LINE__, (int)__ret);    \
            return 1;                                                                  \
        }                                                                              \
    } while (0)

int32_t main()
{
    const int32_t outter = 16, inner = 16;
    const int32_t elem = outter * inner;
    const size_t fBytes = (size_t)elem * sizeof(float);
    const size_t lBytes = (size_t)inner * sizeof(float);

    CHECK_ACL(aclInit(nullptr));
    CHECK_ACL(aclrtSetDevice(0));
    aclrtStream stream = nullptr;
    CHECK_ACL(aclrtCreateStream(&stream));

    float *sHost = nullptr, *dHost = nullptr, *lHost = nullptr;
    uint8_t *sDev = nullptr, *dDev = nullptr, *lDev = nullptr;
    CHECK_ACL(aclrtMallocHost((void **)&sHost, fBytes));
    CHECK_ACL(aclrtMallocHost((void **)&dHost, fBytes));
    CHECK_ACL(aclrtMallocHost((void **)&lHost, lBytes));
    CHECK_ACL(aclrtMalloc((void **)&sDev, fBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&dDev, fBytes, ACL_MEM_MALLOC_HUGE_FIRST));
    CHECK_ACL(aclrtMalloc((void **)&lDev, lBytes, ACL_MEM_MALLOC_HUGE_FIRST));

    for (int32_t i = 0; i < elem; i++) sHost[i] = 1.0f;
    CHECK_ACL(aclrtMemcpy(sDev, fBytes, sHost, fBytes, ACL_MEMCPY_HOST_TO_DEVICE));

    ACLRT_LAUNCH_KERNEL(k_custom)(1, stream, sDev, dDev, lDev);
    CHECK_ACL(aclrtSynchronizeStream(stream));

    CHECK_ACL(aclrtMemcpy(dHost, fBytes, dDev, fBytes, ACL_MEMCPY_DEVICE_TO_HOST));
    CHECK_ACL(aclrtMemcpy(lHost, lBytes, lDev, lBytes, ACL_MEMCPY_DEVICE_TO_HOST));

    int errors = 0;
    // Each output row must equal [1,2,3,...,16].
    for (int32_t r = 0; r < outter; r++) {
        for (int32_t c = 0; c < inner; c++) {
            float expect = (float)(c + 1);
            float v = dHost[r * inner + c];
            if (fabsf(v - expect) > 1e-3f) {
                if (errors < 5) printf("[CHECK] dst[%d][%d] = %f (expect %f)\n", r, c, v, expect);
                errors++;
            }
        }
    }
    // lastRow must equal the prefix sum of the final input row -> [1,2,...,16].
    for (int32_t c = 0; c < inner; c++) {
        float expect = (float)(c + 1);
        if (fabsf(lHost[c] - expect) > 1e-3f) {
            if (errors < 8) printf("[CHECK] lastRow[%d] = %f (expect %f)\n", c, lHost[c], expect);
            errors++;
        }
    }
    printf("dst row0=[%g,%g,...,%g] lastRow=[%g,%g,...,%g] errors=%d\n",
           dHost[0], dHost[1], dHost[inner - 1], lHost[0], lHost[1], lHost[inner - 1], errors);

    // Emit the PASS/FAIL marker BEFORE ACL teardown.
    if (errors == 0) printf("CUMSUM SIMULATION PASSED\n");
    else             printf("CUMSUM SIMULATION FAILED (%d errors)\n", errors);
    fflush(stdout);

    CHECK_ACL(aclrtFree(sDev));
    CHECK_ACL(aclrtFree(dDev));
    CHECK_ACL(aclrtFree(lDev));
    CHECK_ACL(aclrtFreeHost(sHost));
    CHECK_ACL(aclrtFreeHost(dHost));
    CHECK_ACL(aclrtFreeHost(lHost));
    CHECK_ACL(aclrtDestroyStream(stream));
    CHECK_ACL(aclrtResetDevice(0));
    CHECK_ACL(aclFinalize());

    return errors == 0 ? 0 : 1;
}
